### ISSUE TITLE
[BUG]到底怎么设置webdav

### ISSUE THREAD

**Issue by inmost888** [NoraH1to/yue#12]
**Describe the bug**
同样的设置，其他软件的webdav可以用，在这里就是 invalid response: No root Multistatus found.
再点一次确认，显示已连接，其实没有连接，刷新页面又是上面错误。
只能本地导入，文件夹一栏一直empty。
反向代理是不是对yue所在的服务器有什么要求，也没成功过。
**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Device: [e.g. iPad mini6]

**Additional context**

**Comment by NoraH1to** [comment]
配置发下，我瞅瞅

**Comment by inmost888** [comment]
是webdav的配置吗

地址 https://miya.teracloud.jp/dav/

自定义目录基础路径 /

用户名 inmost888
密码 pSqy3cP7QnjefYK2

**Comment by NoraH1to** [comment]
> 是webdav的配置吗
> 
> 地址 https://miya.teracloud.jp/dav/
> 
> 自定义目录基础路径 /
> 
> 用户名 inmost888 密码 pSqy3cP7QnjefYK2

你使用的服务商 webdav 服务不支持跨域访问，同时也没法走 vercel 提供的反代，被 302 重定向了～

这是纯前端应用的局限性，有两个解决方案：

1. 可以尝试下其它的服务商？我个人在用坚果云，自建 alist 也是支持跨域访问的。
2. 自建一个反代服务，伪装好请求头，让服务商无法判断是否通过反代发起请求。

**Comment by inmost888** [comment]
多谢，还是用alist搞好了。
